# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0bbbb75a1fc18dc6c78397d98c719d2afc2ccf2b06105159df0d03ea6c3006c9ef32014f37f703708400156a851e4c0df4543fb83fa961b2f264f94fa059f1d

test:
  secret_key_base: 8cfcab192f8cee7f4966dec79604e4a8bd6bd1bbb39bed5669e9229df8c3a9945c4c99d6ed8590705d0a04e3596aa4a72426f1d3156c0ece454bdbcf0c0f98bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
